package library;

public enum Category {
    FICTION, NONFICTION, SCIENCE, HISTORY, TECHNOLOGY, ART, PHILOSOPHY, RELIGION, EDUCATION, MEDICINE, ENGINEERING, MATHEMATICS, BIOGRAPHY, CHILDREN, POETRY, DRAMA, TRAVEL, COOKING, SPORTS, MUSIC, LAW, POLITICS, BUSINESS, COMICS, ASTRONOMY, PSYCHOLOGY, OTHER
}
